### ISSUE TITLE
PHP Notice messages

### ISSUE THREAD

**Issue by budda** [chrismeller/nodeping#1]
Can you clean up the PHP noticed your class generates please?

```
PHP Notice:  Undefined index: id in /Users/mcarter/Code/bcd-utility-server/php-scripts/pishrundeck/NodePing_php/nodeping.php on line 53
PHP Notice:  Undefined index: _id in /Users/mcarter/Code/bcd-utility-server/php-scripts/pishrundeck/NodePing_php/nodeping.php on line 55
PHP Notice:  Undefined index: url in /Users/mcarter/Code/bcd-utility-server/php-scripts/pishrundeck/NodePing_php/nodeping.php on line 58
PHP Notice:  Undefined index: version in /Users/mcarter/Code/bcd-utility-server/php-scripts/pishrundeck/NodePing_php/nodeping.php on line 6
```

**Comment by budda** [comment]
The first two 'id' ones only occur if no customerid is passed in to the constructor.

**Comment by chrismeller** [comment]
Are you sure those are errors being thrown by this library? None of the line numbers correspond to anything in the [class file](https://github.com/chrismeller/nodeping/blob/master/nodeping.php). There is also no `customerid` parameter to the constructor, only `$token` and `$account`, which is never actually used.

**Comment by budda** [comment]
Gah. Sorry. It's that official one over at https://github.com/NodePing/NodePing_php which is giving the jip! :)
